[package]
name = "wasmlanche-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { workspace = true }
sdk-macros = { path = "../sdk-macros" }
thiserror = { workspace = true }

[dev-dependencies]
wasmtime = "14"

[features]
build = []
