# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: TokenVM Load Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    continue-on-error: true
    strategy:
      matrix:
        level: [v1, v2, v3] # v4 is not supported
    runs-on:
      labels: ubuntu-20.04-32
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          # - name: Install fio
          #   run: sudo apt-get -y install fio
          # - name: Run disk tests
          #   working-directory: ./examples/tokenvm
          #   shell: bash
          #   run: scripts/tests.disk.sh
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
      - name: Run load tests
        working-directory: ./examples/tokenvm
        shell: bash
        run: GOAMD64=${{ matrix.level }} scripts/tests.load.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
